/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new player account and profile.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in with email and password.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Rotate an existing refresh token for a new token pair.
         */
        post: operations["refresh_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke a refresh token on sign-out.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Retrieve currently authenticated user and player profile.
         */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete My Data
         * @description Apple App Store & GDPR Account Deletion.
         *     Deletes personal data and anonymizes historical match records.
         */
        delete: operations["delete_my_data_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Update profile information.
         */
        patch: operations["update_profile_me_profile_patch"];
        trace?: never;
    };
    "/me/communication-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Communication Settings
         * @description Get player communication toggles.
         */
        get: operations["get_communication_settings_me_communication_settings_get"];
        /**
         * Put Communication Settings
         * @description Update communication preferences.
         */
        put: operations["put_communication_settings_me_communication_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Version
         * @description Check app version compatibility for mobile and web clients.
         */
        get: operations["get_app_version_app_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote Cart Endpoint
         * @description Calculate exact server-side pricing quote with tier rules and discounts.
         */
        post: operations["quote_cart_endpoint_cart_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a new pending order and Stripe Checkout Session.
         */
        post: operations["create_checkout_session_checkout_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Handle Stripe payment webhooks idempotently.
         */
        post: operations["stripe_webhook_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order Status
         * @description Retrieve order status and item lines for checkout result polling.
         */
        get: operations["get_order_status_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Match
         * @description Submit a reported match score with format validation and rematch limits.
         */
        post: operations["report_match_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Match Score
         * @description Opponent confirms a reported match score.
         */
        post: operations["confirm_match_score_matches__match_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispute Match Score
         * @description Opponent disputes a reported score, starting a 24h cooling-off window.
         */
        post: operations["dispute_match_score_matches__match_id__dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{division_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Division Roster
         * @description Get opponent roster with contact details (strictly gated to paid division enrollees).
         */
        get: operations["list_division_roster_divisions__division_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Scores Feed
         * @description Retrieve public market-wide feed of latest confirmed match scores.
         */
        get: operations["latest_scores_feed_scores_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{division_id}/playoffs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Playoffs
         * @description Generate the single-elimination championship playoff draw for a division.
         */
        post: operations["generate_playoffs_divisions__division_id__playoffs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{division_id}/playoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Playoffs
         * @description Retrieve all tournament brackets (championship & consolation) for a division.
         */
        get: operations["get_playoffs_divisions__division_id__playoffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playoffs/matches/{match_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Score
         * @description Report a playoff match score and advance the winner to the next round.
         */
        post: operations["report_score_playoffs_matches__match_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Compatible Partners
         * @description Find compatible hitting partners for current user within ±0.5 NTRP in their market.
         */
        get: operations["get_compatible_partners_partners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courts
         * @description List tennis courts in the Frankfurt market with amenity filters.
         */
        get: operations["list_courts_courts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courts/{court_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Court
         * @description Retrieve full court detail with player reviews and ratings.
         */
        get: operations["get_court_courts__court_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courts/{court_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Court Review
         * @description Submit a rating (1-5) and review for a tennis court.
         */
        post: operations["post_court_review_courts__court_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/poty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Poty Leaderboard
         * @description Retrieve the annual Player of the Year (POTY) rankings.
         */
        get: operations["get_poty_leaderboard_community_poty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/referral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Referral Info
         * @description Retrieve personal referral code, shareable link, and reward balance.
         */
        get: operations["get_referral_info_community_referral_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Devices
         * @description List active push notification devices for the current user.
         */
        get: operations["list_user_devices_devices_get"];
        put?: never;
        /**
         * Register Push Device
         * @description Register or refresh an Expo push notification token for the current user.
         */
        post: operations["register_push_device_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{push_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unregister Push Device
         * @description Deactivate a registered push token for the current user.
         */
        delete: operations["unregister_push_device_devices__push_token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Notification History
         * @description Retrieve recent notification history for the current user.
         */
        get: operations["list_user_notification_history_notifications_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/kickoff/{division_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Kickoff Broadcast
         * @description Trigger kickoff broadcast notification job for a division.
         */
        post: operations["trigger_kickoff_broadcast_jobs_kickoff__division_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/nudges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Inactive Player Nudges
         * @description Trigger weekly inactive player reminder job for user's market.
         */
        post: operations["trigger_inactive_player_nudges_jobs_nudges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/auto-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Auto Confirm Matches
         * @description Trigger match auto-confirmation job for user's market.
         */
        post: operations["trigger_auto_confirm_matches_jobs_auto_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Database Backup
         * @description Trigger nightly database backup job.
         */
        post: operations["trigger_database_backup_jobs_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulk-placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk place players into a division */
        post: operations["bulk_placement_admin_bulk_placement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transfer-player": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer a player between divisions */
        post: operations["transfer_player_admin_transfer_player_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/resolve-dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a match dispute and recalculate standings */
        post: operations["resolve_dispute_admin_resolve_dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manage-strike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm, appeal, or dismiss a discipline strike */
        post: operations["manage_strike_admin_manage_strike_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/void-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void a match result and update standings */
        post: operations["void_match_admin_void_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Service liveness and market status check.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Programs
         * @description List available league programs in the current market.
         */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Program Divisions
         * @description List divisions belonging to a given program.
         */
        get: operations["list_program_divisions_programs__program_id__divisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{division_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Division Standings
         * @description Retrieve computed standings for a division, sorted by domain rules.
         */
        get: operations["get_division_standings_divisions__division_id__standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminActionResponse */
        AdminActionResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Audit Id */
            audit_id: string;
        };
        /** AppVersionResponse */
        AppVersionResponse: {
            /** Platform */
            platform: string;
            /** Current Version */
            current_version: string;
            /** Minimum Version */
            minimum_version: string;
            /** Is Update Required */
            is_update_required: boolean;
            /** Update Url */
            update_url?: string | null;
        };
        /** BulkPlacementRequest */
        BulkPlacementRequest: {
            /**
             * Division Id
             * @description Target division ID for placement
             */
            division_id: string;
            /**
             * User Ids
             * @description List of user IDs to place into division
             */
            user_ids: string[];
        };
        /** CheckoutSessionResponse */
        CheckoutSessionResponse: {
            /** Order Id */
            order_id: string;
            /** Checkout Url */
            checkout_url: string;
            /** Session Id */
            session_id: string;
        };
        /** CommunicationSettingsResponse */
        CommunicationSettingsResponse: {
            /** Email Kickoff */
            email_kickoff: boolean;
            /** Email Reminders */
            email_reminders: boolean;
            /** Email Results */
            email_results: boolean;
            /** Push Kickoff */
            push_kickoff: boolean;
            /** Push Reminders */
            push_reminders: boolean;
            /** Push Results */
            push_results: boolean;
        };
        /** CommunicationSettingsUpdate */
        CommunicationSettingsUpdate: {
            /** Email Kickoff */
            email_kickoff?: boolean | null;
            /** Email Reminders */
            email_reminders?: boolean | null;
            /** Email Results */
            email_results?: boolean | null;
            /** Push Kickoff */
            push_kickoff?: boolean | null;
            /** Push Reminders */
            push_reminders?: boolean | null;
            /** Push Results */
            push_results?: boolean | null;
        };
        /** CourtDetailResponse */
        CourtDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Address */
            address: string;
            /** Postal Code */
            postal_code: string;
            /** City */
            city: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Num Courts */
            num_courts: number;
            /** Surface */
            surface: string;
            /** Has Lights */
            has_lights: boolean;
            /** Is Indoor */
            is_indoor: boolean;
            /** Has Hitting Wall */
            has_hitting_wall: boolean;
            /** Booking Url */
            booking_url?: string | null;
            /**
             * Average Rating
             * @default 0
             */
            average_rating: number;
            /**
             * Review Count
             * @default 0
             */
            review_count: number;
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["CourtReviewResponse"][];
        };
        /** CourtResponse */
        CourtResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Address */
            address: string;
            /** Postal Code */
            postal_code: string;
            /** City */
            city: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Num Courts */
            num_courts: number;
            /** Surface */
            surface: string;
            /** Has Lights */
            has_lights: boolean;
            /** Is Indoor */
            is_indoor: boolean;
            /** Has Hitting Wall */
            has_hitting_wall: boolean;
            /** Booking Url */
            booking_url?: string | null;
            /**
             * Average Rating
             * @default 0
             */
            average_rating: number;
            /**
             * Review Count
             * @default 0
             */
            review_count: number;
        };
        /** CourtReviewResponse */
        CourtReviewResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
            /** Created At */
            created_at: string;
        };
        /** CreateCheckoutSessionRequest */
        CreateCheckoutSessionRequest: {
            /** Program Ids */
            program_ids: string[];
            /**
             * Success Url
             * @default http://localhost:8081/checkout/result?session_id={CHECKOUT_SESSION_ID}
             */
            success_url: string;
            /**
             * Cancel Url
             * @default http://localhost:8081/join
             */
            cancel_url: string;
        };
        /** CreateCourtReviewRequest */
        CreateCourtReviewRequest: {
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /** DeviceResponse */
        DeviceResponse: {
            /** Id */
            id: string;
            /** Push Token */
            push_token: string;
            /** Platform */
            platform: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DisputeMatchRequest */
        DisputeMatchRequest: {
            /** Reason */
            reason: string;
        };
        /** DivisionResponse */
        DivisionResponse: {
            /** Id */
            id: string;
            /** Programid */
            programId: string;
            /** Name */
            name: string;
            /** Ratingband */
            ratingBand: string;
            /** Playerscount */
            playersCount: number;
        };
        /** GeneratePlayoffsRequest */
        GeneratePlayoffsRequest: {
            /**
             * Min Wins
             * @default 5
             */
            min_wins: number;
            /**
             * Enable Veteran Seeding
             * @default true
             */
            enable_veteran_seeding: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Market */
            market: string;
            /** Timezone */
            timezone: string;
        };
        /** LatestScoreFeedItem */
        LatestScoreFeedItem: {
            /** Id */
            id: string;
            /** Winner Name */
            winner_name: string;
            /** Loser Name */
            loser_name: string;
            /** Score Line */
            score_line: string;
            /** Division Name */
            division_name: string;
            /** Date Str */
            date_str: string;
        };
        /** ManageStrikeRequest */
        ManageStrikeRequest: {
            /**
             * Strike Id
             * @description Discipline strike ID
             */
            strike_id: string;
            /**
             * Action
             * @description 'confirm', 'dismiss', or 'appeal'
             */
            action: string;
            /**
             * Reason
             * @description Administrative reason for action
             */
            reason: string;
        };
        /** MatchResponse */
        MatchResponse: {
            /** Id */
            id: string;
            /** Division Id */
            division_id: string;
            /** Winner Id */
            winner_id: string;
            /** Loser Id */
            loser_id: string;
            /** Winner Name */
            winner_name: string;
            /** Loser Name */
            loser_name: string;
            /** Format */
            format: string;
            /** Outcome Type */
            outcome_type: string;
            /** Sets Summary */
            sets_summary: string;
            /** Status */
            status: string;
            /** Played At */
            played_at: string;
        };
        /** NotificationHistoryItem */
        NotificationHistoryItem: {
            /** Id */
            id: string;
            /** Channel */
            channel: string;
            /** Event Type */
            event_type: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderItemResponse */
        OrderItemResponse: {
            /** Program Id */
            program_id: string;
            /** Unit Price Cents */
            unit_price_cents: number;
        };
        /** OrderResponse */
        OrderResponse: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /** User Id */
            user_id: string;
            /** Status */
            status: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Currency */
            currency: string;
            /** Items */
            items: components["schemas"]["OrderItemResponse"][];
        };
        /** POTYItemResponse */
        POTYItemResponse: {
            /** Rank */
            rank: number;
            /** Player Id */
            player_id: string;
            /** Display Name */
            display_name: string;
            /** Total Points */
            total_points: number;
            /** Matches Played */
            matches_played: number;
            /** Matches Won */
            matches_won: number;
            /** Distinct Opponents */
            distinct_opponents: number;
            /** Home Area */
            home_area?: string | null;
        };
        /** PartnerMatchResponse */
        PartnerMatchResponse: {
            /** Player Id */
            player_id: string;
            /** Display Name */
            display_name: string;
            /** Rating */
            rating?: string | null;
            /** Home Area */
            home_area?: string | null;
            /**
             * Is Daytime
             * @default false
             */
            is_daytime: boolean;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
        };
        /** PlayerProfileResponse */
        PlayerProfileResponse: {
            /** Display Name */
            display_name: string;
            /** Phone */
            phone: string;
            /** Rating */
            rating: string;
            /** Home Area */
            home_area: string;
            /** Is Daytime */
            is_daytime: boolean;
            /** Veteran Match Count */
            veteran_match_count: number;
            /** Is Anonymized */
            is_anonymized: boolean;
        };
        /** PlayerProfileUpdate */
        PlayerProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Home Area */
            home_area?: string | null;
            /** Is Daytime */
            is_daytime?: boolean | null;
        };
        /** PlayoffBracketResponse */
        PlayoffBracketResponse: {
            /** Id */
            id: string;
            /** Division Id */
            division_id: string;
            /** Bracket Type */
            bracket_type: string;
            /** Bracket Size */
            bracket_size: number;
            /** Total Rounds */
            total_rounds: number;
            /** Status */
            status: string;
            /** Rounds */
            rounds: {
                [key: string]: components["schemas"]["PlayoffMatchResponse"][];
            };
        };
        /** PlayoffMatchResponse */
        PlayoffMatchResponse: {
            /** Id */
            id: string;
            /** Round Number */
            round_number: number;
            /** Match Number */
            match_number: number;
            player1?: components["schemas"]["PlayoffPlayerSummary"] | null;
            player2?: components["schemas"]["PlayoffPlayerSummary"] | null;
            winner?: components["schemas"]["PlayoffPlayerSummary"] | null;
            /** Score Summary */
            score_summary?: string | null;
            /**
             * Is Bye
             * @default false
             */
            is_bye: boolean;
            /** Deadline */
            deadline?: string | null;
            /** Next Match Id */
            next_match_id?: string | null;
        };
        /** PlayoffPlayerSummary */
        PlayoffPlayerSummary: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Seed Number */
            seed_number?: number | null;
        };
        /** ProgramResponse */
        ProgramResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
            /** Status */
            status: string;
            /** Pricecents */
            priceCents: number;
            /** Currency */
            currency: string;
        };
        /** QuoteItemResponse */
        QuoteItemResponse: {
            /** Program Id */
            program_id: string;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Tier Applied */
            tier_applied: string;
        };
        /** QuoteRequest */
        QuoteRequest: {
            /** Program Ids */
            program_ids: string[];
        };
        /** QuoteResponse */
        QuoteResponse: {
            /** Items */
            items: components["schemas"]["QuoteItemResponse"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Discount Cents */
            discount_cents: number;
            /** Final Cost Cents */
            final_cost_cents: number;
            /** Applied Credit Id */
            applied_credit_id?: string | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
        };
        /** ReferralInfoResponse */
        ReferralInfoResponse: {
            /** Referral Code */
            referral_code: string;
            /** Referral Link */
            referral_link: string;
            /** Reward Credit Cents */
            reward_credit_cents: number;
            /** Completed Referrals Count */
            completed_referrals_count: number;
            /** Pending Referrals Count */
            pending_referrals_count: number;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterDeviceRequest */
        RegisterDeviceRequest: {
            /**
             * Push Token
             * @description Expo push notification token
             */
            push_token: string;
            /**
             * Platform
             * @description Device platform (ios, android, web)
             * @default ios
             */
            platform: string;
        };
        /** ReportPlayoffScoreRequest */
        ReportPlayoffScoreRequest: {
            /** Winner Id */
            winner_id: string;
            /** Score Summary */
            score_summary: string;
        };
        /** ResolveDisputeRequest */
        ResolveDisputeRequest: {
            /**
             * Dispute Id
             * @description Match dispute ID
             */
            dispute_id: string;
            /**
             * Resolution
             * @description Resolution: 'resolved_upheld' or 'resolved_changed'
             */
            resolution: string;
            /**
             * Admin Notes
             * @description Reasoning and notes for dispute resolution
             */
            admin_notes: string;
            /**
             * Corrected Sets
             * @description Optional corrected sets if resolution is resolved_changed
             */
            corrected_sets?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** RosterPlayerResponse */
        RosterPlayerResponse: {
            /** Player Id */
            player_id: string;
            /** Display Name */
            display_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Rating */
            rating: string;
            /** Home Area */
            home_area: string;
            /** Is Daytime */
            is_daytime: boolean;
        };
        /** SetScoreInput */
        SetScoreInput: {
            /** Winner */
            winner: number;
            /** Loser */
            loser: number;
            /**
             * Super Tiebreak
             * @default false
             */
            super_tiebreak: boolean;
        };
        /** StandingRowResponse */
        StandingRowResponse: {
            /** Rank */
            rank: number;
            /** Playerid */
            playerId: string;
            /** Playername */
            playerName: string;
            /** Homearea */
            homeArea: string;
            /** Isdaytime */
            isDaytime: boolean;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Gameswon */
            gamesWon: number;
            /** Gameslost */
            gamesLost: number;
            /** Gamespct */
            gamesPct: number;
            /** Gamespctdisplay */
            gamesPctDisplay: string;
            /** Playoffindicator */
            playoffIndicator: string;
            /** Isplayoffeligible */
            isPlayoffEligible: boolean;
        };
        /** SubmitMatchRequest */
        SubmitMatchRequest: {
            /** Division Id */
            division_id: string;
            /** Opponent Id */
            opponent_id: string;
            /**
             * I Am Winner
             * @default true
             */
            i_am_winner: boolean;
            /**
             * Format
             * @default best_of_three
             */
            format: string;
            /**
             * Outcome Type
             * @default played
             */
            outcome_type: string;
            /** Sets */
            sets?: components["schemas"]["SetScoreInput"][];
            /** Minutes Waited */
            minutes_waited?: number | null;
            /** Hours Before Match */
            hours_before_match?: number | null;
            /**
             * Is Rain Exempt
             * @default false
             */
            is_rain_exempt: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TransferPlayerRequest */
        TransferPlayerRequest: {
            /**
             * User Id
             * @description User ID to transfer
             */
            user_id: string;
            /**
             * From Division Id
             * @description Current division ID
             */
            from_division_id: string;
            /**
             * To Division Id
             * @description Target division ID
             */
            to_division_id: string;
            /**
             * Reason
             * @description Administrative reason for transfer
             */
            reason: string;
        };
        /** UserLoginRequest */
        UserLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRegisterRequest */
        UserRegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Rating
             * @default 3.5
             */
            rating: string;
            /**
             * Home Area
             * @default Sachsenhausen
             */
            home_area: string;
            /**
             * Is Daytime
             * @default false
             */
            is_daytime: boolean;
            /**
             * Market Slug
             * @default frankfurt
             */
            market_slug: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            profile?: components["schemas"]["PlayerProfileResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoidMatchRequest */
        VoidMatchRequest: {
            /**
             * Match Id
             * @description Match ID to void
             */
            match_id: string;
            /**
             * Reason
             * @description Administrative reason for voiding match
             */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_my_data_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_profile_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_communication_settings_me_communication_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunicationSettingsResponse"];
                };
            };
        };
    };
    put_communication_settings_me_communication_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunicationSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunicationSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_version_app_version_get: {
        parameters: {
            query?: {
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_cart_endpoint_cart_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_session_checkout_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: {
                "stripe-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_status_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_match_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_match_score_matches__match_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_match_score_matches__match_id__dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_division_roster_divisions__division_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                division_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPlayerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_scores_feed_scores_latest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestScoreFeedItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_playoffs_divisions__division_id__playoffs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                division_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GeneratePlayoffsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayoffBracketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playoffs_divisions__division_id__playoffs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                division_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayoffBracketResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_score_playoffs_matches__match_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportPlayoffScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayoffMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_compatible_partners_partners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerMatchResponse"][];
                };
            };
        };
    };
    list_courts_courts_get: {
        parameters: {
            query?: {
                /** @description Filter by surface (clay, hard, carpet, grass) */
                surface?: string | null;
                /** @description Filter by floodlights */
                has_lights?: boolean | null;
                /** @description Filter indoor/outdoor */
                is_indoor?: boolean | null;
                /** @description Filter hitting wall */
                has_hitting_wall?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_court_courts__court_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                court_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_court_review_courts__court_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                court_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourtReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_poty_leaderboard_community_poty_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["POTYItemResponse"][];
                };
            };
        };
    };
    get_referral_info_community_referral_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralInfoResponse"];
                };
            };
        };
    };
    list_user_devices_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
        };
    };
    register_push_device_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_push_device_devices__push_token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                push_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_notification_history_notifications_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationHistoryItem"][];
                };
            };
        };
    };
    trigger_kickoff_broadcast_jobs_kickoff__division_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                division_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_inactive_player_nudges_jobs_nudges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_auto_confirm_matches_jobs_auto_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_database_backup_jobs_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    bulk_placement_admin_bulk_placement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkPlacementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_player_admin_transfer_player_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferPlayerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_dispute_admin_resolve_dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDisputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_strike_admin_manage_strike_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageStrikeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_match_admin_void_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_programs_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"][];
                };
            };
        };
    };
    list_program_divisions_programs__program_id__divisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_division_standings_divisions__division_id__standings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                division_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingRowResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
