"""initial_schema

Revision ID: 25465db304ad
Revises:
Create Date: 2026-09-28 09:50:39.988369

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25465db304ad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_markets_slug"), "markets", ["slug"], unique=True)
    op.create_table(
        "processed_webhook_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_webhook_events_stripe_event_id"),
        "processed_webhook_events",
        ["stripe_event_id"],
        unique=True,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changes_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_market_id"), "audit_logs", ["market_id"], unique=False)
    op.create_table(
        "courts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("num_courts", sa.Integer(), nullable=False),
        sa.Column("surface", sa.String(length=30), nullable=False),
        sa.Column("has_lights", sa.Boolean(), nullable=False),
        sa.Column("is_indoor", sa.Boolean(), nullable=False),
        sa.Column("has_hitting_wall", sa.Boolean(), nullable=False),
        sa.Column("booking_url", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courts_market_id"), "courts", ["market_id"], unique=False)
    op.create_index(op.f("ix_courts_slug"), "courts", ["slug"], unique=True)
    op.create_table(
        "programs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("program_type", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programs_market_id"), "programs", ["market_id"], unique=False)
    op.create_table(
        "regions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_regions_market_id"), "regions", ["market_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_market_id"), "users", ["market_id"], unique=False)
    op.create_table(
        "communication_preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("email_kickoff", sa.Boolean(), nullable=False),
        sa.Column("email_reminders", sa.Boolean(), nullable=False),
        sa.Column("email_results", sa.Boolean(), nullable=False),
        sa.Column("push_kickoff", sa.Boolean(), nullable=False),
        sa.Column("push_reminders", sa.Boolean(), nullable=False),
        sa.Column("push_results", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_communication_preferences_user_id"),
        "communication_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "court_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("court_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["court_id"], ["courts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_court_reviews_court_id"), "court_reviews", ["court_id"], unique=False)
    op.create_index(op.f("ix_court_reviews_user_id"), "court_reviews", ["user_id"], unique=False)
    op.create_table(
        "credits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("credit_type", sa.String(length=30), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=True),
        sa.Column("discount_pct", sa.Float(), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_consumed", sa.Boolean(), nullable=False),
        sa.Column("consumed_order_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credits_user_id"), "credits", ["user_id"], unique=False)
    op.create_table(
        "divisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rating_band", sa.String(length=20), nullable=False),
        sa.Column("playoff_min_wins", sa.Integer(), nullable=False),
        sa.Column("new_player_min_matches", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_divisions_market_id"), "divisions", ["market_id"], unique=False)
    op.create_index(op.f("ix_divisions_program_id"), "divisions", ["program_id"], unique=False)
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_logs_event_type"), "notification_logs", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_notification_logs_user_id"), "notification_logs", ["user_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("applied_credit_id", sa.String(length=36), nullable=True),
        sa.Column("stripe_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_market_id"), "orders", ["market_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_orders_stripe_session_id"), "orders", ["stripe_session_id"], unique=True
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "player_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("rating", sa.String(length=10), nullable=False),
        sa.Column("home_area", sa.String(length=100), nullable=False),
        sa.Column("is_daytime", sa.Boolean(), nullable=False),
        sa.Column("veteran_match_count", sa.Integer(), nullable=False),
        sa.Column("is_anonymized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_profiles_market_id"), "player_profiles", ["market_id"], unique=False
    )
    op.create_index(op.f("ix_player_profiles_user_id"), "player_profiles", ["user_id"], unique=True)
    op.create_table(
        "referrals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("referrer_id", sa.String(length=36), nullable=False),
        sa.Column("referred_user_id", sa.String(length=36), nullable=True),
        sa.Column("referral_code", sa.String(length=30), nullable=False),
        sa.Column("reward_credit_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["referred_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_referral_code"), "referrals", ["referral_code"], unique=True)
    op.create_index(
        op.f("ix_referrals_referred_user_id"), "referrals", ["referred_user_id"], unique=False
    )
    op.create_index(op.f("ix_referrals_referrer_id"), "referrals", ["referrer_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "user_devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("push_token", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_devices_push_token"), "user_devices", ["push_token"], unique=True)
    op.create_index(op.f("ix_user_devices_user_id"), "user_devices", ["user_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("division_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enrollments_division_id"), "enrollments", ["division_id"], unique=False
    )
    op.create_index(op.f("ix_enrollments_market_id"), "enrollments", ["market_id"], unique=False)
    op.create_index(op.f("ix_enrollments_program_id"), "enrollments", ["program_id"], unique=False)
    op.create_index(op.f("ix_enrollments_user_id"), "enrollments", ["user_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("division_id", sa.String(length=36), nullable=False),
        sa.Column("winner_id", sa.String(length=36), nullable=False),
        sa.Column("loser_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=30), nullable=False),
        sa.Column("outcome_type", sa.String(length=30), nullable=False),
        sa.Column("sets_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reporter_id", sa.String(length=36), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["loser_id"], ["player_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["winner_id"], ["player_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_division_id"), "matches", ["division_id"], unique=False)
    op.create_index(op.f("ix_matches_loser_id"), "matches", ["loser_id"], unique=False)
    op.create_index(op.f("ix_matches_market_id"), "matches", ["market_id"], unique=False)
    op.create_index(op.f("ix_matches_winner_id"), "matches", ["winner_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "playoff_brackets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("division_id", sa.String(length=36), nullable=False),
        sa.Column("bracket_type", sa.String(length=30), nullable=False),
        sa.Column("bracket_size", sa.Integer(), nullable=False),
        sa.Column("total_rounds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playoff_brackets_division_id"), "playoff_brackets", ["division_id"], unique=False
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("stripe_refund_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_table(
        "standing_rows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("division_id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("games_won", sa.Integer(), nullable=False),
        sa.Column("games_lost", sa.Integer(), nullable=False),
        sa.Column("distinct_opponents", sa.Integer(), nullable=False),
        sa.Column("is_playoff_eligible", sa.Boolean(), nullable=False),
        sa.Column("playoff_indicator", sa.String(length=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["player_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_standing_rows_division_id"), "standing_rows", ["division_id"], unique=False
    )
    op.create_index(
        op.f("ix_standing_rows_player_id"), "standing_rows", ["player_id"], unique=False
    )
    op.create_table(
        "match_disputes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("disputer_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("cooling_off_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["disputer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_disputes_match_id"), "match_disputes", ["match_id"], unique=False
    )
    op.create_table(
        "playoff_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bracket_id", sa.String(length=36), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("match_number", sa.Integer(), nullable=False),
        sa.Column("player1_id", sa.String(length=36), nullable=True),
        sa.Column("player2_id", sa.String(length=36), nullable=True),
        sa.Column("winner_id", sa.String(length=36), nullable=True),
        sa.Column("score_summary", sa.String(length=100), nullable=True),
        sa.Column("is_bye", sa.Boolean(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_match_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bracket_id"], ["playoff_brackets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player1_id"], ["player_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player2_id"], ["player_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["winner_id"], ["player_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playoff_matches_bracket_id"), "playoff_matches", ["bracket_id"], unique=False
    )
    op.create_table(
        "strikes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("market_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("calendar_year", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strikes_market_id"), "strikes", ["market_id"], unique=False)
    op.create_index(op.f("ix_strikes_user_id"), "strikes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strikes_user_id"), table_name="strikes")
    op.drop_index(op.f("ix_strikes_market_id"), table_name="strikes")
    op.drop_table("strikes")
    op.drop_index(op.f("ix_playoff_matches_bracket_id"), table_name="playoff_matches")
    op.drop_table("playoff_matches")
    op.drop_index(op.f("ix_match_disputes_match_id"), table_name="match_disputes")
    op.drop_table("match_disputes")
    op.drop_index(op.f("ix_standing_rows_player_id"), table_name="standing_rows")
    op.drop_index(op.f("ix_standing_rows_division_id"), table_name="standing_rows")
    op.drop_table("standing_rows")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_playoff_brackets_division_id"), table_name="playoff_brackets")
    op.drop_table("playoff_brackets")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_matches_winner_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_market_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_loser_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_division_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_enrollments_user_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_program_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_market_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_division_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_user_devices_user_id"), table_name="user_devices")
    op.drop_index(op.f("ix_user_devices_push_token"), table_name="user_devices")
    op.drop_table("user_devices")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_referrals_referrer_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_referred_user_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_referral_code"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_player_profiles_user_id"), table_name="player_profiles")
    op.drop_index(op.f("ix_player_profiles_market_id"), table_name="player_profiles")
    op.drop_table("player_profiles")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_stripe_session_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_market_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_notification_logs_user_id"), table_name="notification_logs")
    op.drop_index(op.f("ix_notification_logs_event_type"), table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index(op.f("ix_divisions_program_id"), table_name="divisions")
    op.drop_index(op.f("ix_divisions_market_id"), table_name="divisions")
    op.drop_table("divisions")
    op.drop_index(op.f("ix_credits_user_id"), table_name="credits")
    op.drop_table("credits")
    op.drop_index(op.f("ix_court_reviews_user_id"), table_name="court_reviews")
    op.drop_index(op.f("ix_court_reviews_court_id"), table_name="court_reviews")
    op.drop_table("court_reviews")
    op.drop_index(
        op.f("ix_communication_preferences_user_id"), table_name="communication_preferences"
    )
    op.drop_table("communication_preferences")
    op.drop_index(op.f("ix_users_market_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_regions_market_id"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_programs_market_id"), table_name="programs")
    op.drop_table("programs")
    op.drop_index(op.f("ix_courts_slug"), table_name="courts")
    op.drop_index(op.f("ix_courts_market_id"), table_name="courts")
    op.drop_table("courts")
    op.drop_index(op.f("ix_audit_logs_market_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_processed_webhook_events_stripe_event_id"), table_name="processed_webhook_events"
    )
    op.drop_table("processed_webhook_events")
    op.drop_index(op.f("ix_markets_slug"), table_name="markets")
    op.drop_table("markets")
    # ### end Alembic commands ###
